cd "$(dirname "$0")/.."
R=assets/raw/player_ref.png
S="Side view facing right, identical character size and feet baseline in every frame. Transparent or plain pure white background, no ground, no shadow, no text, no borders."
bash tools/gen.sh player_idle "Pixel-art game sprite sheet: the SAME character as the reference image, shown 4 times side by side in ONE horizontal row, 4 equal columns, frames of a subtle breathing IDLE animation (standing still, chest and shoulders rise slightly, scarf sways gently). $S" $R &
bash tools/gen.sh player_attack "Pixel-art game sprite sheet: the SAME character as the reference image holding a crude stone axe, shown 4 times side by side in ONE horizontal row, 4 equal columns, frames of an ATTACK swing: frame1 wind-up axe raised behind head, frame2 swinging overhead, frame3 impact axe forward and down in front, frame4 recovering. $S" $R &
bash tools/gen.sh player_die "Pixel-art game sprite sheet: the SAME character as the reference image, shown 4 times side by side in ONE horizontal row, 4 equal columns, frames of a DEATH animation: frame1 hit and staggering back, frame2 knees buckling, frame3 falling backwards, frame4 lying flat on the ground on his back. Same scale in every frame. Transparent or plain pure white background, no shadow, no text, no borders." $R &
bash tools/gen.sh zombie_walk "Pixel-art game sprite sheet, same detailed 16-bit pixel art style as the reference image: a shambling green-skinned ZOMBIE in torn grey shirt and ragged brown pants, arms reaching forward, shown 4 times side by side in ONE horizontal row, 4 equal columns, frames of a slow limping walk cycle. $S" $R &
bash tools/gen.sh boar_walk "Pixel-art game sprite sheet, same detailed 16-bit pixel art style as the reference image: a wild brown BOAR with small tusks, shown 4 times side by side in ONE horizontal row, 4 equal columns, frames of a trotting walk cycle, side view facing right, identical size and baseline. Transparent or plain pure white background, no ground, no shadow, no text, no borders." $R &
bash tools/gen.sh props "Pixel-art game assets, same detailed 16-bit pixel art style as the reference image (do NOT draw the character): 4 separate objects side by side in ONE horizontal row, 4 equal columns, all standing on the same baseline: 1) a tall leafy green oak tree, 2) a tall dark green pine tree, 3) a large grey boulder rock, 4) a green bush with red berries. Front/side view. Transparent or plain pure white background, no ground, no shadow, no text, no borders." $R &
bash tools/gen.sh campfire "Pixel-art game sprite sheet, same detailed 16-bit pixel art style as the reference image (do NOT draw the character): a CAMPFIRE with logs and a ring of stones, shown 4 times side by side in ONE horizontal row, 4 equal columns, frames of flickering flame animation (flame shape changes each frame). Transparent or plain pure white background, no shadow, no text, no borders." $R &
bash tools/gen.sh items "Pixel-art game item icons, same detailed 16-bit pixel art style as the reference image (do NOT draw the character): 6 separate icons side by side in ONE horizontal row, 6 equal columns: 1) a wood log, 2) a grey stone, 3) a raw meat steak, 4) red berries cluster, 5) cooked meat on bone, 6) a red heart. Transparent or plain pure white background, no text, no borders." $R &
wait
echo ALLDONE
